[env:m5stick-c-plus]
platform = espressif32
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_deps =
    https://github.com/m5stack/M5StickC-Plus.git

build_flags =
    -DCORE_DEBUG_LEVEL=0

board_build.partitions = no_ota.csv
